# Generated by Django 5.1 on 2025-01-06 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_drinkcategory_foodcategory_remove_item_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drinkcategory',
            options={'ordering': ['position'], 'verbose_name': 'Nápojový lístek - kategorie', 'verbose_name_plural': 'Nápojový lístek - kategorie'},
        ),
        migrations.AlterModelOptions(
            name='drinkitem',
            options={'verbose_name': 'Nápojový lístek - produkty', 'verbose_name_plural': 'Nápojový lístek - produkty'},
        ),
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'ordering': ['position'], 'verbose_name': 'Jídelní lístek - kategorie', 'verbose_name_plural': 'Jídelní lístek - kategorie'},
        ),
        migrations.AlterModelOptions(
            name='fooditem',
            options={'verbose_name': 'Jídelní lístek - produkty', 'verbose_name_plural': 'Jídelní lístek - produkty'},
        ),
        migrations.AddField(
            model_name='drinkcategory',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Position for ordering categories in the final template. Lower values appear first.', verbose_name='Pozice v tabulce'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Position for ordering categories in the final template. Lower values appear first.', verbose_name='Pozice v tabulce'),
        ),
        migrations.AlterField(
            model_name='drinkcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='drinkitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.drinkcategory', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='drinkitem',
            name='price',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.foodcategory', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
