# Generated by Django 5.1 on 2025-01-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_drinkcategory_options_alter_drinkitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkitem',
            name='position',
            field=models.PositiveIntegerField(default=10, verbose_name='Pozice v tabulce'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='position',
            field=models.PositiveIntegerField(default=10, verbose_name='Pozice v tabulce'),
        ),
        migrations.AlterField(
            model_name='drinkcategory',
            name='position',
            field=models.PositiveIntegerField(default=10, help_text='Position for ordering categories in the final template. Lower values appear first.', verbose_name='Pozice v tabulce'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='position',
            field=models.PositiveIntegerField(default=10, help_text='Position for ordering categories in the final template. Lower values appear first.', verbose_name='Pozice v tabulce'),
        ),
    ]
