# Generated by Django 5.1 on 2025-01-06 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_drinkitem_position_fooditem_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drinkitem',
            options={'ordering': ['position'], 'verbose_name': 'Nápojový lístek - produkty', 'verbose_name_plural': 'Nápojový lístek - produkty'},
        ),
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ['position'], 'verbose_name': 'Jídelní lístek - produkty', 'verbose_name_plural': 'Jídelní lístek - produkty'},
        ),
    ]
