# Generated by Django 5.1 on 2025-01-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_drinkitem_options_alter_fooditem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Název')),
                ('image', models.ImageField(upload_to='carousel_home/', verbose_name='Obrázek')),
            ],
            options={
                'verbose_name': 'Úvodní fotka',
                'verbose_name_plural': 'Úvodní fotky',
            },
        ),
    ]
