# Generated by Django 5.1 on 2025-01-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Jméno a příjmení')),
                ('persons', models.IntegerField(verbose_name='Počet osob')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254)),
                ('note', models.TextField(blank=True, null=True, verbose_name='Poznámka')),
                ('date_arrival', models.DateField(verbose_name='Příjezd')),
                ('date_departure', models.DateField(verbose_name='Odjezd')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
            ],
            options={
                'verbose_name': 'Zpráva',
                'verbose_name_plural': 'Zprávy',
                'ordering': ['-date_created'],
            },
        ),
    ]
