# Generated by Django 5.1 on 2025-01-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Název')),
                ('price_main_season', models.CharField(max_length=200, verbose_name='Cena hlavní sezóna')),
                ('price_off_season', models.CharField(max_length=200, verbose_name='Cena mimo sezónu')),
                ('position', models.IntegerField(verbose_name='Pozice v tabulce')),
            ],
            options={
                'verbose_name': 'Služba',
                'verbose_name_plural': 'Služby (Ceník)',
                'ordering': ['position'],
            },
        ),
    ]
