# Generated by Django 5.1 on 2025-01-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Název')),
                ('row_one', models.TextField(blank=True, null=True, verbose_name='Řádek 1')),
                ('row_two', models.TextField(blank=True, null=True, verbose_name='Řádek 2')),
                ('row_three', models.TextField(blank=True, null=True, verbose_name='Řádek 3')),
                ('row_four', models.TextField(blank=True, null=True, verbose_name='Řádek 4')),
                ('row_five', models.TextField(blank=True, null=True, verbose_name='Řádek 5')),
                ('position', models.IntegerField(verbose_name='Pozice v tabulce')),
            ],
            options={
                'verbose_name': 'Poznámka',
                'verbose_name_plural': 'Poznámky (Ceník)',
                'ordering': ['position'],
            },
        ),
    ]
