# Generated by Django 5.1 on 2025-01-06 13:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='row_five',
        ),
        migrations.RemoveField(
            model_name='note',
            name='row_four',
        ),
        migrations.RemoveField(
            model_name='note',
            name='row_one',
        ),
        migrations.RemoveField(
            model_name='note',
            name='row_three',
        ),
        migrations.RemoveField(
            model_name='note',
            name='row_two',
        ),
        migrations.AddField(
            model_name='note',
            name='text',
            field=ckeditor.fields.RichTextField(default='-'),
        ),
    ]
