# Generated by Django 5.1 on 2025-01-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0004_remove_note_row_five_remove_note_row_four_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Název')),
                ('image', models.ImageField(upload_to='accommodation_photos/', verbose_name='Obrázek')),
            ],
        ),
    ]
