# Generated by Django 5.1 on 2025-01-06 14:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0005_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulek')),
                ('text', ckeditor.fields.RichTextField(default='-')),
            ],
        ),
    ]
