# Generated by Django 5.1 on 2025-01-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0007_carousel_alter_photo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='introduction',
            options={'verbose_name': 'Úvodní text', 'verbose_name_plural': 'Úvodní text'},
        ),
    ]
