# Generated by Django 5.1 on 2025-01-07 17:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Název')),
                ('image', models.ImageField(upload_to='activities_photos/', verbose_name='Obrázek')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Popisek')),
            ],
            options={
                'verbose_name': 'Fotka',
                'verbose_name_plural': 'Galerie',
            },
        ),
    ]
