# Generated by Django 5.1 on 2024-08-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_contact_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
