# Generated by Django 5.1 on 2024-08-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_contact_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_arrival',
            field=models.DateField(verbose_name='Příjezd'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_departure',
            field=models.DateField(verbose_name='Odjezd'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Jméno a příjmení'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='persons',
            field=models.IntegerField(verbose_name='Počet osob'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Název'),
        ),
    ]
