# Generated by Django 5.1 on 2024-08-27 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_contact_date_arrival_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vytvořeno'),
        ),
    ]
