# Generated by Django 5.1 on 2025-01-05 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_homecarousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
