# Generated by Django 5.1 on 2025-01-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_delete_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeCarousel',
            new_name='Carousel',
        ),
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Úvodní fotka', 'verbose_name_plural': 'Úvodní fotky'},
        ),
    ]
