# Generated by Django 5.1 on 2025-01-07 10:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Odběratel',
                'verbose_name_plural': 'Odběratelé',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Předmět')),
                ('message', ckeditor.fields.RichTextField(verbose_name='Zpráva')),
                ('send', models.BooleanField(default=False, verbose_name='Odeslat')),
                ('recipients', models.ManyToManyField(to='newsletter.subscriber', verbose_name='Odběratelé')),
            ],
            options={
                'verbose_name': 'Šablona',
                'verbose_name_plural': 'Šablony',
            },
        ),
    ]
