# Generated by Django 5.1 on 2025-01-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='recipients',
            field=models.ManyToManyField(blank=True, to='newsletter.subscriber', verbose_name='Odběratelé'),
        ),
    ]
