# Generated by Django 5.1 on 2025-01-07 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_emailtemplate_recipients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.emailtemplate')),
            ],
        ),
    ]
