# Generated by Django 5.1 on 2025-01-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='send',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='sent',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='send',
            field=models.BooleanField(default=False, verbose_name='Odeslat'),
        ),
    ]
